export const itemCards = [
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "120119644",
        name: "Dal { Plain }",
        category: "Veg Gravy",
        imageId: "90c0c8460851ac03e16ad10f73c3959a",
        inStock: 1,
        isVeg: 1,
        price: 23000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "3.0",
            ratingCount: "10 ratings",
            ratingCountV2: "10",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#D9EFEC", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_medium",
            ratingTextColor: "rating_medium",
            ratingCountTextColor: "rating_medium",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422570",
        menuFilterIds: ["VEG"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "123575207",
        name: "Dal Tadka",
        category: "Veg Gravy",
        imageId: "f078bb04f145cf801f53553836f96dba",
        inStock: 1,
        isVeg: 1,
        price: 25000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.6",
            ratingCount: "19 ratings",
            ratingCountV2: "19",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "47205420",
        menuFilterIds: ["VEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "123575211",
        name: "Palak Paneer",
        category: "Veg Gravy",
        imageId: "651a954ed4ca7a20cb56e17eee305488",
        inStock: 1,
        isVeg: 1,
        price: 25000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.3",
            ratingCount: "24 ratings",
            ratingCountV2: "24",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "71079717",
        menuFilterIds: ["VEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "123575215",
        name: "Veg Kolhapuri",
        category: "Veg Gravy",
        imageId: "5ae5d04d3a2c3f4c6df8229fb7499635",
        inStock: 1,
        isVeg: 1,
        price: 25000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "3.0",
            ratingCount: "7 ratings",
            ratingCountV2: "7",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#D9EFEC", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_medium",
            ratingTextColor: "rating_medium",
            ratingCountTextColor: "rating_medium",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "49584544",
        menuFilterIds: ["VEG"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "123575217",
        name: "Paneer Butter Masala",
        category: "Veg Gravy",
        imageId: "22f9b2f972120f550c804e5ee5d04552",
        inStock: 1,
        isVeg: 1,
        price: 25000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {
          text: "Bestseller",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        isBestseller: true,
        ratings: {
          aggregatedRating: {
            rating: "4.4",
            ratingCount: "176 ratings",
            ratingCountV2: "176",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "48097359",
        menuFilterIds: ["bestseller", "VEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509555",
        name: "Paneer Kadai",
        category: "Veg Gravy",
        imageId: "81c1ac408149ef670e0d388794e831bb",
        inStock: 1,
        isVeg: 1,
        price: 25000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.3",
            ratingCount: "55 ratings",
            ratingCountV2: "55",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422646",
        menuFilterIds: ["VEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509557",
        name: "Paneer Tikka Masala",
        category: "Veg Gravy",
        imageId: "pkk6op4gh1xelay0niyi",
        inStock: 1,
        isVeg: 1,
        price: 25000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "3.1",
            ratingCount: "44 ratings",
            ratingCountV2: "44",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#D9EFEC", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_medium",
            ratingTextColor: "rating_medium",
            ratingCountTextColor: "rating_medium",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422659",
        menuFilterIds: ["VEG"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509561",
        name: "Paneer Kaju Masala",
        category: "Veg Gravy",
        imageId: "d964890d7d9d9c7be0be3941e0b088e3",
        inStock: 1,
        isVeg: 1,
        price: 25000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "3.8",
            ratingCount: "51 ratings",
            ratingCountV2: "51",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#D9EFEC", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_medium",
            ratingTextColor: "rating_medium",
            ratingCountTextColor: "rating_medium",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422647",
        menuFilterIds: ["VEG"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "120119691",
        name: "Kaju Masala",
        category: "Veg Gravy",
        imageId: "ad12bcf49d9622b6555d6ee3d646440d",
        inStock: 1,
        isVeg: 1,
        price: 25000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.3",
            ratingCount: "38 ratings",
            ratingCountV2: "38",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "44834164",
        menuFilterIds: ["VEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509653",
        name: "Chicken Fry",
        category: "Non-Veg Starters",
        imageId: "zf4mbsih5btv3cfftsbl",
        inStock: 1,
        price: 27500,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "NONVEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "3.7",
            ratingCount: "8 ratings",
            ratingCountV2: "8",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#D9EFEC", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_medium",
            ratingTextColor: "rating_medium",
            ratingCountTextColor: "rating_medium",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        imageBadges: [
          {
            imageId: "merch_bau/High%20Protein%201_1.png",
          },
        ],
        parentId: "13422541",
        menuFilterIds: ["EATRIGHT", "NONVEG"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509674",
        name: "Chicken Tikka",
        category: "Non-Veg Starters",
        imageId: "30dc672231e9d3c5d2f8a8c82f10ecc6",
        inStock: 1,
        price: 27000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "NONVEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "3.9",
            ratingCount: "14 ratings",
            ratingCountV2: "14",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#D9EFEC", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_medium",
            ratingTextColor: "rating_medium",
            ratingCountTextColor: "rating_medium",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422562",
        menuFilterIds: ["NONVEG"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509676",
        name: "Chicken Hariyali Tikka",
        category: "Non-Veg Starters",
        imageId: "jvqeg2tangqgjpvcmace",
        inStock: 1,
        price: 27000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "NONVEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.8",
            ratingCount: "12 ratings",
            ratingCountV2: "12",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422543",
        menuFilterIds: ["NONVEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509679",
        name: "Mutton Fry",
        category: "Non-Veg Starters",
        imageId: "a366574f5f33578ca165f9a0fafcc751",
        inStock: 1,
        price: 30000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "NONVEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.6",
            ratingCount: "25 ratings",
            ratingCountV2: "25",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422627",
        menuFilterIds: ["NONVEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "120119569",
        name: "Green Salad        ",
        category: "Bread/Roti",
        imageId: "b6a17d907384c9ea45c8bd48223b8372",
        inStock: 1,
        isVeg: 1,
        price: 9500,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.5",
            ratingCount: "10 ratings",
            ratingCountV2: "10",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "68774001",
        menuFilterIds: ["VEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509563",
        name: "Butter Roti    ",
        category: "Bread/Roti",
        imageId: "ze1egg3vjq742pbh8wcg",
        inStock: 1,
        isVeg: 1,
        price: 4500,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.2",
            ratingCount: "118 ratings",
            ratingCountV2: "118",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422532",
        menuFilterIds: ["VEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509566",
        name: "Kulcha  ",
        category: "Bread/Roti",
        imageId: "dunpzxblcq6hitrkda4z",
        inStock: 1,
        isVeg: 1,
        price: 5500,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "3.7",
            ratingCount: "36 ratings",
            ratingCountV2: "36",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#D9EFEC", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_medium",
            ratingTextColor: "rating_medium",
            ratingCountTextColor: "rating_medium",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422604",
        menuFilterIds: ["VEG"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509567",
        name: "Butter Kulcha  ",
        category: "Bread/Roti",
        imageId: "d90uhunif09npxfo7ngi",
        inStock: 1,
        isVeg: 1,
        price: 6000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {
          text: "Bestseller",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        isBestseller: true,
        ratings: {
          aggregatedRating: {
            rating: "4.3",
            ratingCount: "141 ratings",
            ratingCountV2: "141",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422529",
        menuFilterIds: ["bestseller", "VEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509570",
        name: "Naan",
        category: "Bread/Roti",
        imageId: "agajay8gvqpctczyzs5c",
        inStock: 1,
        isVeg: 1,
        price: 6500,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "3.7",
            ratingCount: "32 ratings",
            ratingCountV2: "32",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#D9EFEC", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_medium",
            ratingTextColor: "rating_medium",
            ratingCountTextColor: "rating_medium",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422636",
        menuFilterIds: ["VEG"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "47509571",
        name: "Butter Naan",
        category: "Bread/Roti",
        imageId: "qjcuxmrnrfgsatadd9qi",
        inStock: 1,
        isVeg: 1,
        price: 7000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.4",
            ratingCount: "123 ratings",
            ratingCountV2: "123",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "13422530",
        menuFilterIds: ["VEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "123575221",
        name: "Paneer Paratha",
        category: "Bread/Roti",
        imageId: "91ba79745de0d85d59e093c7067410d4",
        inStock: 1,
        isVeg: 1,
        price: 9900,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.3",
            ratingCount: "14 ratings",
            ratingCountV2: "14",
          },
          ratingsPresentationConfig: {
            bgGradient: {
              colours: ["#C8F9E5", "#00FFFFFF"],
              gradientDirection: "GRADIENT_DIRECTION_LEFT_TO_RIGHT",
            },
            ratingIconColor: "rating_very_good",
            ratingTextColor: "rating_very_good",
            ratingCountTextColor: "rating_very_good",
            ratingFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
            ratingCountFontName: "FONT_NAME_V2_OVERLINE_NEUTRAL_BOLD",
          },
        },
        parentId: "51087600",
        menuFilterIds: ["VEG", "toprated"],
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
];
